### ISSUE TITLE
Babel package name changing for 6.x

### ISSUE THREAD

**Issue by jamen** [b52/electron-es6-react#2]
Hey, since babel updated to 6.0.0 apparently not too long ago, it changed a bit of it's packages around...

``` javascript
require('babel/register');
```

Will no longer work.

Their new registry package is under `babel-core/register`, however simply replacing the current registries with that one in the scripts didn't work for me...  They may have changed it up quite a bit from what it used to be.

I couldn't figure out a solution...  So you may want to poke around in babel-core a bit and see if you can figure it out yourself, or just use the older version of babel.

**Comment by aomader** [comment]
I see what you mean, I ran into the problem myself. I haven't found a fix for that either.

**Comment by jamen** [comment]
An update on this: 

Based on what I know from the time I've used Babel since creating this issue, I know that Babel now uses a plugin system, and so it's react transpiling is now separate from the main package and placed into a package.  You probably have to load that plugin somehow in the bootstrap (and in the render).

This is also true for ES2015 features, they separated it into a new plugin.

Essentially, since updating to 6.x, the babel core is now just a empty shell, and the main components aren't included by default.
