### ISSUE TITLE
require('babel-register') is really slow

### ISSUE THREAD

**Issue by lmatteis** [b52/electron-es6-react#4]
Have you noticed how `require('babel-register')` is really slow? To see the changes I run a `ctrl+R` and it takes ~5 seconds to show the changes.

**Comment by aomader** [comment]
Of course, there is a performance penalty, since the hook transpiles all the code during startup. This means, the larger your project, the longer the startup takes. However, this should not affect the runtime after this initial transpiling.

**Comment by lmatteis** [comment]
Right I see. How do you deal with code changes then? Do you have something that only compiles the things that changed and swaps them directly from the page? I guess the boilerplate react electron project might be a better place to start if I want that functionality.

**Comment by aomader** [comment]
I don't know of any like that. I'm sorry.
