### ISSUE TITLE
Don't render to document.body directly

### ISSUE THREAD

**Issue by MartinMajewski** [b52/electron-es6-react#7]
Hi,

thank you very much for your minimal boilerplate code. Finally a really minimal example! 👍 

One thing that should be modified though, is the react DOM rendering.
Rendering with

`ReactDOM.render(<Main />, document.body);`

results in a chromium warning

> warning.js:36 Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.

The better solution:

Change the rendering call to 

`ReactDOM.render(<Main />, document.getElementById('react_container'));`

and add the following between the <body></body> tags of the index.html file:

`<div id="react_container"></div>`

Warning will then go away and the example stays minimal :-)

Best wishes,
Martin

**Comment by aomader** [comment]
Sorry I didn't respond timely. However, in the meantime @swbullis prepared a fix for it, which I just merged. 👍
